# This script will setup XiangShan environment variables
# Auto-generated by setup-by-conda.sh

# >>> conda-activate >>>
if ! type conda >& /dev/null; then echo "::ERROR:: you must have conda in your environment first"; return 1; fi; eval "$(conda shell.bash hook)"
conda activate /fact_home/yanqinli/my-eda/xs-workspace/xs-env/.conda-env
# <<< conda-activate <<<

# >>> xs-env-vars >>>

export XS_PROJECT_ROOT=$(pwd)
export NEMU_HOME="$XS_PROJECT_ROOT/NEMU"
export AM_HOME="$XS_PROJECT_ROOT/nexus-am"
export NOOP_HOME="$XS_PROJECT_ROOT/XiangShan"
export DRAMSIM3_HOME="$XS_PROJECT_ROOT/DRAMsim3"
export gem5_home="$XS_PROJECT_ROOT/gem5"
export TUTORIAL_HOME="$XS_PROJECT_ROOT/tutorial"
export READY2RUN_HOME="$TUTORIAL_HOME/ready-to-run"

# RISC-V tools path
export RISCV="${RISCV:-$CONDA_PREFIX/riscv-tools}"
export PATH="$RISCV/bin:$PATH"

# compiler include path (for emu compile)
export CPLUS_INCLUDE_PATH="$CONDA_PREFIX/include:$CPLUS_INCLUDE_PATH"
export C_INCLUDE_PATH="$CONDA_PREFIX/include:$C_INCLUDE_PATH"

# Mill path
if [ -f "$HOME/bin/mill" ]; then
    export PATH="$HOME/bin:$PATH"
fi

# <<< xs-env-vars <<<

# Fallback: if it is not edited by setup-by-conda.sh, use the default path
if [ -z "$XS_PROJECT_ROOT" ]; then
    export XS_PROJECT_ROOT=$(pwd)
    export NEMU_HOME=$(pwd)/NEMU
    export AM_HOME=$(pwd)/nexus-am
    export NOOP_HOME=$(pwd)/XiangShan
    export DRAMSIM3_HOME=$(pwd)/DRAMsim3
    export gem5_home=$(pwd)/gem5

    echo SET XS_PROJECT_ROOT: ${XS_PROJECT_ROOT}
    echo SET NOOP_HOME \(XiangShan RTL Home\): ${NOOP_HOME}
    echo SET NEMU_HOME: ${NEMU_HOME}
    echo SET AM_HOME: ${AM_HOME}
    echo SET DRAMSIM3_HOME: ${DRAMSIM3_HOME}
    echo SET gem5_home: ${gem5_home}

    # For tutorial
    export TUTORIAL_HOME=$(pwd)/tutorial
    export READY2RUN_HOME=${TUTORIAL_HOME}/ready-to-run

    echo SET TUTORIAL_HOME: ${TUTORIAL_HOME}
    echo SET READY2RUN_HOME: ${READY2RUN_HOME}
fi