# This script will setup XiangShan environment variables
# Auto-generated by setup-conda.sh

# >>> conda-activate >>>
# Conda activation code will be inserted here by setup-conda.sh
# <<< conda-activate <<<

# >>> xs-env-vars >>>

export XS_PROJECT_ROOT="/fact_home/yanqinli/my-eda/xs-workspace/xs-env"
export NEMU_HOME="$XS_PROJECT_ROOT/NEMU"
export AM_HOME="$XS_PROJECT_ROOT/nexus-am"
export NOOP_HOME="$XS_PROJECT_ROOT/XiangShan"
export DRAMSIM3_HOME="$XS_PROJECT_ROOT/DRAMsim3"
export gem5_home="$XS_PROJECT_ROOT/gem5"
export TUTORIAL_HOME="$XS_PROJECT_ROOT/tutorial"
export READY2RUN_HOME="$TUTORIAL_HOME/ready-to-run"

# RISC-V 工具链路径 (来自 riscv-tools conda 包)
export RISCV="${RISCV:-$CONDA_PREFIX/riscv-tools}"
export PATH="$RISCV/bin:$PATH"

# <<< xs-env-vars <<<

# Fallback: 如果没有被 setup-conda.sh 修改，使用默认路径
if [ -z "$XS_PROJECT_ROOT" ]; then
    export XS_PROJECT_ROOT=$(pwd)
    export NEMU_HOME=$(pwd)/NEMU
    export AM_HOME=$(pwd)/nexus-am
    export NOOP_HOME=$(pwd)/XiangShan
    export DRAMSIM3_HOME=$(pwd)/DRAMsim3
    export gem5_home=$(pwd)/gem5

    echo SET XS_PROJECT_ROOT: ${XS_PROJECT_ROOT}
    echo SET NOOP_HOME \(XiangShan RTL Home\): ${NOOP_HOME}
    echo SET NEMU_HOME: ${NEMU_HOME}
    echo SET AM_HOME: ${AM_HOME}
    echo SET DRAMSIM3_HOME: ${DRAMSIM3_HOME}
    echo SET gem5_home: ${gem5_home}

    # For tutorial
    export TUTORIAL_HOME=$(pwd)/tutorial
    export READY2RUN_HOME=${TUTORIAL_HOME}/ready-to-run

    echo SET TUTORIAL_HOME: ${TUTORIAL_HOME}
    echo SET READY2RUN_HOME: ${READY2RUN_HOME}
fi