#!/bin/bash
# XiangShan Conda Environment Setup Script
# Usage: source setup-by-conda.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ============================================================================
# Helper Functions
# ============================================================================

# Activate conda environment
activate_conda() {
    if type conda &> /dev/null; then
        eval "$(conda shell.bash hook)" 2>/dev/null
        return 0
    fi

    local CONDA_PATH="$HOME/miniconda3"
    if [ -f "$CONDA_PATH/etc/profile.d/conda.sh" ]; then
        source "$CONDA_PATH/etc/profile.d/conda.sh"
        return 0
    fi

    if [ -f "$HOME/miniconda3/bin/conda" ]; then
        eval "$($HOME/miniconda3/bin/conda shell.bash hook)" 2>/dev/null || true
        return 0
    fi

    echo "[WARN] conda not found"
    return 1
}

# Append content to env.sh between markers
update_env_file() {
    local file="$1"
    local marker="$2"
    local content="$3"
    local marker_start="# >>> ${marker} >>>"
    local marker_end="# <<< ${marker} <<<"

    if [ ! -f "$file" ]; then
        cat > "$file" << 'EOF'
#!/bin/bash
# XiangShan Environment Variables
# Auto-generated by setup-by-conda.sh

EOF
    fi

    python3 -c "
import sys
marker_start = '''$marker_start'''
marker_end = '''$marker_end'''
content = '''$content'''

with open('$file', 'r') as f:
    lines = f.readlines()

output = []
in_block = False
found_start = False

for line in lines:
    if marker_start in line:
        in_block = True
        found_start = True
        output.append(line)
        output.append(content + '\n')
    elif marker_end in line and in_block:
        in_block = False
        output.append(line)
    elif not in_block:
        output.append(line)

if not found_start:
    output.append('\n')
    output.append(marker_start + '\n')
    output.append(content + '\n')
    output.append(marker_end + '\n')

with open('$file', 'w') as f:
    f.writelines(output)
" 2>/dev/null
}

# ============================================================================
# Install Miniconda
# ============================================================================
install_miniconda() {
    if command -v conda &> /dev/null; then
        echo "[OK] Conda already installed: $(conda --version)"
        return 0
    fi

    echo "[INFO] Installing Miniconda..."

    local CONDA_PATH="$HOME/miniconda3"
    if [ -d "$CONDA_PATH" ]; then
        echo "[OK] Miniconda exists at $CONDA_PATH"
        return 0
    fi

    local ARCH=$(uname -m)
    local CONDA_URL=""

    case $ARCH in
        x86_64)
            CONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
            ;;
        aarch64|arm64)
            CONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh"
            ;;
        *)
            echo "[ERROR] Unsupported architecture: $ARCH"
            return 1
            ;;
    esac

    cd /tmp
    if ! wget -q "$CONDA_URL" -O miniconda.sh 2>/dev/null; then
        echo "[ERROR] Failed to download Miniconda"
        return 1
    fi

    if ! bash miniconda.sh -b -p "$CONDA_PATH" 2>/dev/null; then
        echo "[ERROR] Failed to install Miniconda"
        rm -f miniconda.sh
        return 1
    fi
    rm -f miniconda.sh

    echo "[OK] Miniconda installed: $CONDA_PATH"
}

# ============================================================================
# Create Conda Environment from Lock File
# ============================================================================
create_conda_env() {
    echo "========== Creating Conda Environment =========="

    activate_conda || return 1

    local LOCK_FILE="$SCRIPT_DIR/conda-reqs/lock/xs-env-linux-64.lock"
    local CONDA_ENV_PATH="$SCRIPT_DIR/.conda-env"

    if [ -d "$CONDA_ENV_PATH" ]; then
        echo "[INFO] Conda environment already exists: $CONDA_ENV_PATH"
        return 0
    fi

    if [ ! -f "$LOCK_FILE" ]; then
        echo "[ERROR] Lock file not found: $LOCK_FILE"
        return 1
    fi

    echo "[INFO] Creating environment from lock file..."
    if ! conda create -y -p "$CONDA_ENV_PATH" --file "$LOCK_FILE" 2>&1; then
        echo "[ERROR] Failed to create conda environment"
        return 1
    fi

    echo "[OK] Conda environment created: $CONDA_ENV_PATH"
}

# ============================================================================
# Setup Environment Variables
# ============================================================================
setup_env_vars() {
    echo "[INFO] Setting up environment variables..."

    local CONDA_ENV_PATH="$SCRIPT_DIR/.conda-env"

    # Conda activation
    local conda_activate='if ! type conda >& /dev/null; then echo "::ERROR:: conda required"; return 1; fi; eval "$(conda shell.bash hook)"'
    update_env_file "$SCRIPT_DIR/env.sh" "conda-activate" \
        "$conda_activate
conda activate $CONDA_ENV_PATH"

    # XiangShan environment variables
    update_env_file "$SCRIPT_DIR/env.sh" "xs-env-vars" "
export XS_PROJECT_ROOT=\"$SCRIPT_DIR\"
export NEMU_HOME=\"\$XS_PROJECT_ROOT/NEMU\"
export AM_HOME=\"\$XS_PROJECT_ROOT/nexus-am\"
export NOOP_HOME=\"\$XS_PROJECT_ROOT/XiangShan\"
export DRAMSIM3_HOME=\"\$XS_PROJECT_ROOT/DRAMsim3\"
export gem5_home=\"\$XS_PROJECT_ROOT/gem5\"
export TUTORIAL_HOME=\"\$XS_PROJECT_ROOT/tutorial\"
export READY2RUN_HOME=\"\$TUTORIAL_HOME/ready-to-run\"

# RISC-V toolchain path (from riscv-tools conda package)
export RISCV=\"\${RISCV:-\$CONDA_PREFIX/riscv-tools}\"
export PATH=\"\$RISCV/bin:\$PATH\"

# Compiler include paths for emu compilation
export CPLUS_INCLUDE_PATH=\"\$CONDA_PREFIX/include:\$CPLUS_INCLUDE_PATH\"
export C_INCLUDE_PATH=\"\$CONDA_PREFIX/include:\$C_INCLUDE_PATH\"

# Mill path (if installed in user directory)
if [ -f \"\$HOME/bin/mill\" ]; then
    export PATH=\"\$HOME/bin:\$PATH\"
fi
"

    echo "[OK] Environment variables configured"
}

# ============================================================================
# Install Mill Build Tool
# ============================================================================
install_mill() {
    echo "[INFO] Installing Mill..."

    local MILL_PATH="$HOME/bin/mill"
    if [ -f "$MILL_PATH" ]; then
        echo "[OK] Mill already installed: $MILL_PATH"
        return 0
    fi

    mkdir -p "$HOME/bin"
    if curl -sL https://github.com/com-lihaoyi/mill/releases/download/0.11.6/0.11.6 > "$MILL_PATH" 2>/dev/null; then
        chmod +x "$MILL_PATH"
        echo "[OK] Mill installed: $MILL_PATH"
    else
        echo "[WARN] Mill download failed, install manually"
    fi
}

# ============================================================================
# Main Setup Flow
# ============================================================================
main() {
    echo "=========================================="
    echo "XiangShan Conda Environment Setup"
    echo "=========================================="

    install_miniconda
    create_conda_env
    install_mill
    setup_env_vars

    echo ""
    echo "=========================================="
    echo "Setup Complete!"
    echo "=========================================="
    echo ""
    echo "To activate environment:"
    echo "  eval \"\$(conda shell.bash hook)\""
    echo "  conda activate .conda-env"
    echo "  source env.sh"
    echo ""
    echo "To verify:"
    echo "  cd NutShell"
    echo "  make verilog && make emu"
    echo "=========================================="
}

main