#!/bin/bash
# XiangShan Conda 环境设置脚本
# 参考 Chipyard build-setup.sh run_step 1 的逻辑
# 用法: source setup-conda.sh

# 不要使用 set -e，因为 sourced 脚本中任何错误都会导致 shell 退出
# set -e
# set -o pipefail

# 获取脚本目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# 默认参数
TOOLCHAIN_TYPE="riscv-tools"

# 帮助信息
usage() {
    echo "Usage: source ${0} [OPTIONS]"
    echo ""
    echo "Options"
    echo "  --help -h           : Display this message"
    echo ""
    echo "参考 Chipyard build-setup.sh run_step 1"
}

# 解析参数
while [ "$1" != "" ]; do
    case $1 in
        -h | --help)
            usage
            return 0
            ;;
        *)
            echo "Invalid option: $1"
            usage
            return 1
            ;;
    esac
    shift
done

# 工具函数 - 更新 env.sh 中的标记内容
replace_content() {
    local file="$1"
    local marker="$2"
    local content="$3"
    local marker_start="# >>> ${marker} >>>"
    local marker_end="# <<< ${marker} <<<"

    # 如果文件不存在，创建基本结构
    if [ ! -f "$file" ]; then
        cat > "$file" << 'HEADER'
#!/bin/bash
# XiangShan Environment Variables
# Auto-generated by setup-conda.sh

HEADER
        return 0
    fi

    # 使用 Python 来避免 sed 跨平台问题
    python3 -c "
import sys
marker_start = '''$marker_start'''
marker_end = '''$marker_end'''
content = '''$content'''

with open('$file', 'r') as f:
    lines = f.readlines()

output = []
in_block = False
found_start = False

for line in lines:
    if marker_start in line:
        in_block = True
        found_start = True
        output.append(line)  # 保留开始标记
        output.append(content + '\n')
    elif marker_end in line and in_block:
        in_block = False
        output.append(line)  # 保留结束标记
    elif not in_block:
        output.append(line)

# 如果标记不存在，追加内容
if not found_start:
    output.append('\n')
    output.append(marker_start + '\n')
    output.append(content + '\n')
    output.append(marker_end + '\n')

with open('$file', 'w') as f:
    f.writelines(output)
" 2>/dev/null

    # 如果 Python 失败，回退使用简单方法
    if [ $? -ne 0 ]; then
        # 简单方法：直接追加到文件末尾
        echo "" >> "$file"
        echo "$marker_start" >> "$file"
        echo "$content" >> "$file"
        echo "$marker_end" >> "$file"
    fi
}

# ============================================
# 安装 Miniconda
# ============================================
install_miniconda() {
    # 检查 conda 是否已安装
    if command -v conda &> /dev/null; then
        echo "[OK] Conda 已安装: $(conda --version)"
        eval "$(conda shell.bash hook)" 2>/dev/null || true
        return 0
    fi

    echo "[INFO] 安装 Miniconda..."

    # 检查权限
    local CONDA_PATH="$HOME/miniconda3"
    if [ -d "$CONDA_PATH" ]; then
        echo "[WARN] Miniconda 已存在于 $CONDA_PATH"
        eval "$($CONDA_PATH/bin/conda shell.bash hook)" 2>/dev/null || true
        return 0
    fi

    local ARCH=$(uname -m)
    local CONDA_URL=""

    case $ARCH in
        x86_64)
            CONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh"
            ;;
        aarch64|arm64)
            CONDA_URL="https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh"
            ;;
        *)
            echo "[ERROR] 不支持的架构: $ARCH"
            return 0  # 不要返回 1，会导致 sourced 脚本退出
            ;;
    esac

    echo "[INFO] 下载 Miniconda..."
    cd /tmp
    if ! wget -q "$CONDA_URL" -O miniconda.sh 2>/dev/null; then
        echo "[ERROR] 下载 Miniconda 失败，请检查网络连接"
        return 0
    fi

    echo "[INFO] 安装 Miniconda 到 $CONDA_PATH..."
    if ! bash miniconda.sh -b -p "$CONDA_PATH" 2>/dev/null; then
        echo "[ERROR] 安装 Miniconda 失败"
        rm -f miniconda.sh
        return 0
    fi
    rm -f miniconda.sh

    # 初始化 conda
    eval "$($CONDA_PATH/bin/conda shell.bash hook)" 2>/dev/null || true
    conda init 2>/dev/null || true

    echo "[OK] Miniconda 安装完成: $CONDA_PATH"
}

# ============================================
# 激活 conda
# ============================================
activate_conda() {
    # 多种方式尝试激活 conda
    if type conda &> /dev/null; then
        eval "$(conda shell.bash hook)" 2>/dev/null
        return 0
    fi

    local CONDA_PATH="$HOME/miniconda3"
    if [ -f "$CONDA_PATH/etc/profile.d/conda.sh" ]; then
        source "$CONDA_PATH/etc/profile.d/conda.sh"
        return 0
    fi

    if [ -f "$HOME/miniconda3/bin/conda" ]; then
        eval "$($HOME/miniconda3/bin/conda shell.bash hook)" 2>/dev/null || true
        return 0
    fi

    echo "[WARN] 无法找到 conda"
    return 0
}

# ============================================
# Run Step 1: Conda 环境设置
# ============================================
run_step_1() {
    echo "========== BEGINNING STEP 1: Conda environment setup =========="

    # 确保 conda 已激活
    activate_conda

    if ! type conda &> /dev/null; then
        echo "[ERROR] Conda 未安装或无法激活"
        return 0
    fi

    local CONDA_REQS="$SCRIPT_DIR/conda-reqs"
    local CONDA_LOCK_REQS="$CONDA_REQS/conda-lock-reqs"
    local LOCKFILE="$CONDA_LOCK_REQS/conda-requirements-$TOOLCHAIN_TYPE-linux-64.conda-lock.yml"

    # 创建锁文件目录
    mkdir -p "$CONDA_LOCK_REQS"

    # 检查锁文件是否已存在
    if [ -f "$LOCKFILE" ]; then
        echo "[INFO] 使用现有锁文件: $LOCKFILE"
    else
        echo "[INFO] 需要生成锁文件..."

        # 创建临时的 conda-lock 环境来加速依赖解析
        local CONDA_LOCK_ENV_PATH="$SCRIPT_DIR/.conda-lock-env"
        echo "[INFO] 创建临时 conda-lock 环境..."

        rm -rf "$CONDA_LOCK_ENV_PATH"

        # 尝试创建 conda-lock 环境
        echo "[INFO] 安装 conda-lock..."
        if ! conda create -y -p "$CONDA_LOCK_ENV_PATH" -c conda-forge conda-lock=2.5.7 2>/dev/null; then
            echo "[WARN] 无法创建临时环境，直接尝试生成锁文件..."
            CONDA_LOCK_ENV_PATH=""
        else
            conda activate "$CONDA_LOCK_ENV_PATH" 2>/dev/null || true
        fi

        # 生成锁文件
        echo "[INFO] 生成锁文件 (这可能需要几分钟)..."

        # 先检查配置文件是否存在
        if [ ! -f "$CONDA_REQS/xs-env-base.yaml" ]; then
            echo "[ERROR] 配置文件不存在: $CONDA_REQS/xs-env-base.yaml"
            return 0
        fi

        local lock_args="-f $CONDA_REQS/xs-env-base.yaml -f $CONDA_REQS/xs-env-extended.yaml -f $CONDA_REQS/riscv-tools.yaml -p linux-64 --lockfile $LOCKFILE"

        if ! conda-lock --no-mamba --no-micromamba $lock_args 2>&1; then
            echo "[ERROR] 生成锁文件失败"
            echo "[INFO] 尝试简化方法: 直接创建环境..."

            # 简化方法：直接使用 conda env create
            local CONDA_ENV_PATH="$SCRIPT_DIR/.conda-env"
            conda create -y -p "$CONDA_ENV_PATH" -c conda-forge -c ucb-bar gcc=13.2 gxx=13.2 openjdk=20 sbt verilator=5.022 riscv-tools=1.0.6 2>/dev/null || true
            conda activate "$CONDA_ENV_PATH" 2>/dev/null || true
            return 0
        fi

        echo "[OK] 锁文件生成: $LOCKFILE"
    fi

    # 检查是否已安装主 conda 环境
    local CONDA_ENV_PATH="$SCRIPT_DIR/.conda-env"
    if [ -d "$CONDA_ENV_PATH" ]; then
        echo "[INFO] Conda 环境已存在: $CONDA_ENV_PATH"
    else
        # 安装主 conda 环境
        echo "[INFO] 安装主 conda 环境到: $CONDA_ENV_PATH"

        if ! conda-lock install --conda "$(which conda)" -p "$CONDA_ENV_PATH" "$LOCKFILE" 2>&1; then
            echo "[WARN] conda-lock 安装失败，尝试直接创建环境..."

            # 简化方法：直接创建环境
            conda create -y -p "$CONDA_ENV_PATH" -c conda-forge -c ucb-bar \
                gcc=13.2 gxx=13.2 openjdk=20 sbt verilator=5.022 riscv-tools=1.0.6 \
                mill firtool clang=18 2>/dev/null || true
        fi
    fi

    conda activate "$CONDA_ENV_PATH" 2>/dev/null || true

    # 生成 conda 激活代码
    local CONDA_ACTIVATE_PREAMBLE='if ! type conda >& /dev/null; then echo "::ERROR:: you must have conda in your environment first"; return 1; fi; eval "$(conda shell.bash hook)"'

    replace_content "$SCRIPT_DIR/env.sh" "conda-activate" \
        "$CONDA_ACTIVATE_PREAMBLE
conda activate $CONDA_ENV_PATH"

    echo "========== STEP 1 COMPLETE =========="
}

# ============================================
# 设置 XiangShan 环境变量
# ============================================
setup_env_vars() {
    echo "[INFO] 设置 XiangShan 环境变量..."

    replace_content "$SCRIPT_DIR/env.sh" "xs-env-vars" "
export XS_PROJECT_ROOT=\"$SCRIPT_DIR\"
export NEMU_HOME=\"\$XS_PROJECT_ROOT/NEMU\"
export AM_HOME=\"\$XS_PROJECT_ROOT/nexus-am\"
export NOOP_HOME=\"\$XS_PROJECT_ROOT/XiangShan\"
export DRAMSIM3_HOME=\"\$XS_PROJECT_ROOT/DRAMsim3\"
export gem5_home=\"\$XS_PROJECT_ROOT/gem5\"
export TUTORIAL_HOME=\"\$XS_PROJECT_ROOT/tutorial\"
export READY2RUN_HOME=\"\$TUTORIAL_HOME/ready-to-run\"

# RISC-V 工具链路径 (来自 riscv-tools conda 包)
export RISCV=\"\${RISCV:-\$CONDA_PREFIX/riscv-tools}\"
export PATH=\"\$RISCV/bin:\$PATH\"

# 设置编译器的 include 路径 (用于 emu 编译)
export CPLUS_INCLUDE_PATH=\"\$CONDA_PREFIX/include:\$CPLUS_INCLUDE_PATH\"
export C_INCLUDE_PATH=\"\$CONDA_PREFIX/include:\$C_INCLUDE_PATH\"

# Mill 路径 (如果安装在用户目录)
if [ -f \"\$HOME/bin/mill\" ]; then
    export PATH=\"\$HOME/bin:\$PATH\"
fi
"

    echo "[OK] 环境变量已设置"
}

# ============================================
# 安装额外工具
# ============================================
install_extra_tools() {
    echo "[INFO] 安装额外工具..."

    # 安装 Mill 到用户目录 (Scala 构建工具)
    local MILL_PATH="$HOME/bin/mill"
    if [ -f "$MILL_PATH" ]; then
        echo "[OK] Mill 已安装: $MILL_PATH"
    else
        echo "[INFO] 安装 Mill 到 $HOME/bin..."
        mkdir -p "$HOME/bin"

        if curl -sL https://github.com/com-lihaoyi/mill/releases/download/0.11.6/0.11.6 > "$MILL_PATH" 2>/dev/null; then
            chmod +x "$MILL_PATH"
            echo "[OK] Mill 安装完成: $MILL_PATH"
            echo "[INFO] 请将 \$HOME/bin 添加到 PATH: export PATH=\"\$HOME/bin:\$PATH\""
        else
            echo "[WARN] Mill 下载失败，可稍后手动安装"
            echo "  mkdir -p \$HOME/bin"
            echo "  curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.6/0.11.6 > \$HOME/bin/mill"
            echo "  chmod +x \$HOME/bin/mill"
        fi
    fi

    echo "[OK] 额外工具安装完成"
}

# ============================================
# 验证环境
# ============================================
verify_env() {
    echo ""
    echo "=========================================="
    echo "环境验证"
    echo "=========================================="

    activate_conda
    conda activate "$SCRIPT_DIR/.conda-env" 2>/dev/null || true

    echo "[1/7] Conda: $(conda --version 2>/dev/null || echo 'FAIL')"
    echo "[2/7] Python: $(python3 --version 2>/dev/null || echo 'FAIL')"
    echo "[3/7] Java: $(java -version 2>&1 | head -1 | cut -d'"' -f2 || echo 'FAIL')"
    echo "[4/7] SBT: $(sbt --version 2>&1 | head -1 || echo 'FAIL')"
    echo "[5/7] Mill: $(mill -i version 2>&1 | head -1 || echo 'FAIL')"
    echo "[6/7] Verilator: $(verilator --version 2>&1 || echo 'FAIL')"
    echo "[7/7] Firtool: $(firtool --version 2>&1 | head -1 || echo 'FAIL')"

    echo ""
    echo "RISC-V 工具链:"
    if [ -n "$RISCV" ] && [ -d "$RISCV" ]; then
        echo "  RISCV: $RISCV"
        if [ -f "$RISCV/bin/riscv64-unknown-linux-gnu-gcc" ]; then
            echo "  GCC: $($RISCV/bin/riscv64-unknown-linux-gnu-gcc --version | head -1)"
        fi
    else
        echo "  RISCV: 等待配置"
    fi

    echo "=========================================="
}

# ============================================
# 主流程
# ============================================
main() {
    echo "=========================================="
    echo "XiangShan Conda Environment Setup"
    echo "参考 Chipyard build-setup.sh run_step 1"
    echo "=========================================="

    # 1. 安装 Miniconda
    install_miniconda

    # 2. Run Step 1: Conda 环境
    run_step_1

    # 3. 安装额外工具
    install_extra_tools

    # 4. 设置环境变量
    setup_env_vars

    # 5. 验证
    verify_env

    echo ""
    echo "=========================================="
    echo "环境设置完成!"
    echo "=========================================="
    echo ""
    echo "激活环境命令:"
    echo "  eval \"\$(conda shell.bash hook)\""
    echo "  conda activate xs-env"
    echo "  source env.sh"
    echo ""
    echo "验证构建:"
    echo "  cd XiangShan"
    echo "  make verilog"
    echo "=========================================="
}

main